//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetGenres", ReplyAction="http://tempuri.org/IService1/GetGenresResponse")]
        ClassLibrary1.Genre[] GetGenres();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetGenres", ReplyAction="http://tempuri.org/IService1/GetGenresResponse")]
        System.Threading.Tasks.Task<ClassLibrary1.Genre[]> GetGenresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAuthors", ReplyAction="http://tempuri.org/IService1/GetAuthorsResponse")]
        ClassLibrary1.Author[] GetAuthors();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAuthors", ReplyAction="http://tempuri.org/IService1/GetAuthorsResponse")]
        System.Threading.Tasks.Task<ClassLibrary1.Author[]> GetAuthorsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPublishers", ReplyAction="http://tempuri.org/IService1/GetPublishersResponse")]
        ClassLibrary1.Publisher[] GetPublishers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPublishers", ReplyAction="http://tempuri.org/IService1/GetPublishersResponse")]
        System.Threading.Tasks.Task<ClassLibrary1.Publisher[]> GetPublishersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBooks", ReplyAction="http://tempuri.org/IService1/GetBooksResponse")]
        ClassLibrary1.Book[] GetBooks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBooks", ReplyAction="http://tempuri.org/IService1/GetBooksResponse")]
        System.Threading.Tasks.Task<ClassLibrary1.Book[]> GetBooksAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : BookStoreClient.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<BookStoreClient.ServiceReference1.IService1>, BookStoreClient.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClassLibrary1.Genre[] GetGenres() {
            return base.Channel.GetGenres();
        }
        
        public System.Threading.Tasks.Task<ClassLibrary1.Genre[]> GetGenresAsync() {
            return base.Channel.GetGenresAsync();
        }
        
        public ClassLibrary1.Author[] GetAuthors() {
            return base.Channel.GetAuthors();
        }
        
        public System.Threading.Tasks.Task<ClassLibrary1.Author[]> GetAuthorsAsync() {
            return base.Channel.GetAuthorsAsync();
        }
        
        public ClassLibrary1.Publisher[] GetPublishers() {
            return base.Channel.GetPublishers();
        }
        
        public System.Threading.Tasks.Task<ClassLibrary1.Publisher[]> GetPublishersAsync() {
            return base.Channel.GetPublishersAsync();
        }
        
        public ClassLibrary1.Book[] GetBooks() {
            return base.Channel.GetBooks();
        }
        
        public System.Threading.Tasks.Task<ClassLibrary1.Book[]> GetBooksAsync() {
            return base.Channel.GetBooksAsync();
        }
    }
}
